# This is a basic workflow that is manually triggered

name: Test-AzureSignTool

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Testing Sign with Github and azure sign tool'
        # Default value if no value is explicitly provided
        default: 'AzureSignTool'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string

env:
  AZURE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.102'              # set this to the dotnet version to use
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  whoami:
    runs-on: windows-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
  signbinaries: # make sure the action works on a clean machine without building
    if: github.actor == 'a-dabo'
    runs-on: windows-latest
    steps:
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install AzureSignTool
      run: dotnet tool install --no-cache --global AzureSignTool --version 6.0.1
  
